const items = [
      {
          category:"ペット",
          source:require('../assets/designs/bspc0001.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0002.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0003.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0004.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0005.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0006.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0007.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0008.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0009.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0010.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0011.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0012.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0013.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0014.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0015.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0016.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0017.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0018.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0019.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0020.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0021.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0022.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0023.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0024.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0025.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0026.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0027.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0028.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0029.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0030.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0031.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0032.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0033.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0034.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0035.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0036.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0037.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0038.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0039.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0040.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0041.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0042.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0043.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0044.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0045.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0046.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0047.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0048.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0049.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0050.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0051.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0052.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0053.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0054.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0055.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0056.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0057.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0058.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0059.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0060.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0061.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0062.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0063.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0064.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0065.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0066.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0067.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0068.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0069.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0070.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0071.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0072.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0073.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0074.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0075.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0076.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0077.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0078.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0079.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0080.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0081.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0082.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0083.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0084.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0085.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0086.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0087.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0088.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0089.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0090.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0091.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0092.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0093.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0094.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0095.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0096.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0097.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0098.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0099.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0100.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0101.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0102.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0103.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0104.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0105.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0106.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0107.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0108.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0109.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0110.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0111.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0112.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0113.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0114.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0115.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0116.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0117.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0118.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0119.jpg'),
      },
      {
          category:"ペット",
          source:require('../assets/designs/bspc0120.jpg'),
      },
]


export default items;